/*
* Name: Bobby Parsons
* Date: 9/25/21
* Email: frparsons@dmacc.edu
*
* Parses a CSV file generated by the previous program
*/

#include <iostream>
#include <fstream>
#include <string>
#include <iomanip>

using namespace std;

const char SEPARATOR = ',';

string INPUT_FILE = "order.csv";

string readToSeparator(string& inputLine, char separator);

int main() {
	string line;
	string sku;
	string quantityStr;
	string priceStr;
	int quantity;
	double price;
	double total = 0;

	ifstream fin;

	fin.open(INPUT_FILE);

	while (!fin.eof()) {
		getline(fin, line);

		if (line.size() > 0) { // check to make sure line isn't empty (such as the last one in the file)
			sku = readToSeparator(line, SEPARATOR);
			quantityStr = readToSeparator(line, SEPARATOR);
			priceStr = readToSeparator(line, SEPARATOR);

			quantity = stoi(quantityStr);
			price = stod(priceStr);

			total += quantity * price;

			cout << sku << ": " << quantityStr << " @ " << priceStr << ": ";
			// set the item subtotal to have a fixed number of decimal places (2), be no less than 6 characters wide, and be right aligned
			cout << fixed << setprecision(2) << setw(6) << right << quantity * price << endl;
		}
	}

	cout << "Total: $" << fixed << setprecision(2) << total << endl;

	fin.close();

	return 0;
}

string readToSeparator(string& inputLine, char separator)
{
	string output;

	// read line in until the separator comes up or line is empty
	while (inputLine[0] != separator && inputLine.size() > 0) {
		output.push_back(inputLine[0]);
		inputLine.erase(0, 1);
	}

	if (inputLine.size() > 0) {
		inputLine.erase(0, 1); // clear the extra comma
	}

	return output;
}

/*
order.csv:
KS944RUR,2,9.99
AT222RUR,1,1.00

output:
KS944RUR: 2 @ 9.99:  19.98
AT222RUR: 1 @ 1.00:   1.00
Total: $20.98
*/